### PR TITLE
Add support for Facebook image and video posts

### PR DESCRIPTION
**Pull request by patsplat**
Currently FB image and video messages are quietly dropped.  This PR passes such messages to API.ai for processing.  If this is a candidate for merge, then I'll follow up with the Individual and Corporate CLA's.

Please review and provide feedback.

What changes would prepare this PR for merge?

### CODE REVIEW

**Comment by patsplat** [comment]
I signed the individual CLA.  The corporate CLA will likely also be necessary.

**Comment by patsplat** [comment]
Ping for feedback?

**Comment by gregseed** [comment]
Please check this in. It is needed for my chatbot!!!

**Comment by patsplat** [comment]
Closing PR due to inactivity

**Pull request closed without merging**
